on:
    push:
      branches:
        - main
jobs:
    build:
      runs-on: ubuntu-latest
  
      steps:
      - name: Checkout repository
        uses: actions/checkout@v2
  
    deploy:
      runs-on: ubuntu-latest
  
      needs: build
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
  
      steps:
      - name: Checkout repository
        uses: actions/checkout@v2
  
      - name: Install pnpm and pm2
        run: |
          npm install -g pnpm
          npm install -g pm2
  
      - name: SSH into VPS and run commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSHKEY }}
          script: |
            # Pull the latest changes if the folder exists
            cd mern-ecommerce-app
            git pull origin main
            
            # Navigate to the server directory
            cd server
  
            # Install server dependencies
            pnpm install
  
            # Stop PM2 process
            pm2 delete raviecom || true
  
            # Start PM2 process
            pm2 start server.js --name raviecom || true
  
            # Navigate to the client directory
            cd .. && cd client
  
            # Install client dependencies
            pnpm install
  
            # Build client
            pnpm run build
  