name: deploy

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Set CI to false
        run: echo "CI=false" >> $GITHUB_ENV    

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.10.0' # Choose a valid Node.js version

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Change to client directory
        run: cd client && pnpm install && pnpm run build

      - name: Change to server directory
        run: cd server && pnpm install

      - name: Commit and Push Changes
        run: |
          git config --global user.email "raviraj32140@gmail.com"
          git config --global user.name "raviraj3214"
          git add -A
          git commit -m "Upload build files"
          git push origin main

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSHKEY }}
          script: cd mern-ecommerce-app && git fetch && git merge origin/main -m "Merge remote-tracking branch into main"
