name: deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

  deploy:
    runs-on: ubuntu-latest

    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: SSH into VPS and run commands
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        port: ${{ secrets.PORT }}
        key: ${{ secrets.SSHKEY }}
        script: |
          # Check if the mern-ecommerce-app folder exists
          if [ ! -d "mern-ecommerce-app" ]; then
            # Clone the repository if it doesn't exist
            git clone https://github.com/raviraj3214/mern-ecommerce-app.git mern-ecommerce-app
          else
            # Pull the latest changes if the folder exists
            cd mern-ecommerce-app
            git pull origin main
            cd ..
          fi

          # Navigate to the server directory
          cd mern-ecommerce-app/server

          # Install server dependencies
          pnpm install

          # Stop PM2 process
          pm2 delete raviecom || true

          # Start PM2 process
          pm2 start server.js --name raviecom || true

          # Navigate to the client directory
          cd .. && cd client

          # Install client dependencies
          pnpm install

          # Build client
          pnpm run build
